[package]
name = "speech_sampler"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
hound = "3.5.1"
voice_activity_detector = "0.2.1"
whisper-rs = { version = "0.15.1", features = ["cuda"] }
